// Services Data Configuration
// This file contains all the data for different services
// Instead of having 15+ separate HTML files, we use this single data file

const SERVICES_DATA = {
  1: {
    id: 1,
    title: "Bouncy Castle",
    description: "Premium bouncy castles for unforgettable birthday parties and events",
    images: [
      "service_01/service1_images/1.jpg",
      "service_01/service1_images/2.jpg",
      "service_01/service1_images/3.jpg",
      "service_01/service1_images/4.jpg",
      "service_01/service1_images/5.jpg",
      "service_01/service1_images/6.jpg",
      "service_01/service1_images/7.jpg",
      "service_01/service1_images/8.jpg",
      "service_01/service1_images/9.jpg",
      "service_01/service1_images/10.jpg",
      "service_01/service1_images/11.jpg",
      "service_01/service1_images/12.jpg",
      "service_01/service1_images/13.jpg",
      "service_01/service1_images/14.jpg",
      "service_01/service1_images/15.jpg",
      "service_01/service1_images/16.jpg",
      "service_01/service1_images/17.jpg",
      "service_01/service1_images/18.jpg"
    ]
  },
  2: {
    id: 2,
    title: "Face Painting and Balloon Bending",
    description: "Professional face painting and balloon artistry for unforgettable events",
    images: [
      "service_02/service2_images/1.jpg",
      "service_02/service2_images/2.jpg",
      "service_02/service2_images/3.jpg",
      "service_02/service2_images/4.jpg",
      "service_02/service2_images/5.jpg",
      "service_02/service2_images/6.jpg",
      "service_02/service2_images/7.jpg",
      "service_02/service2_images/8.jpg",
      "service_02/service2_images/9.jpg",
      "service_02/service2_images/10.jpg",
      "service_02/service2_images/11.jpg",
      "service_02/service2_images/12.jpg",
      "service_02/service2_images/13.jpg",
      "service_02/service2_images/14.jpg"
    ]
  },
  3: {
    id: 3,
    title: "Birthday Party Packages",
    description: "Create magical birthday celebrations with our comprehensive party packages",
    images: [
      "service_03/service3_images/1.jpg",
      "service_03/service3_images/2.jpg",
      "service_03/service3_images/3.jpg",
      "service_03/service3_images/4.jpg",
      "service_03/service3_images/5.jpg",
      "service_03/service3_images/6.jpg",
      "service_03/service3_images/7.jpg",
      "service_03/service3_images/8.jpg",
      "service_03/service3_images/9.jpg"
    ]
  },
  4: {
    id: 4,
    title: "Book Magician for Birthday Party",
    description: "Professional magicians to create wonder and amazement at your event",
    images: [
      "service_04/service4_images/1.jpg",
      "service_04/service4_images/2.jpg",
      "service_04/service4_images/3.jpg",
      "service_04/service4_images/4.jpg",
      "service_04/service4_images/5.jpg",
      "service_04/service4_images/6.jpg",
      "service_04/service4_images/7.jpg",
      "service_04/service4_images/8.jpg",
      "service_04/service4_images/9.jpg",
      "service_04/service4_images/10.jpg",
      "service_04/service4_images/11.jpg",
      "service_04/service4_images/12.jpg",
      "service_04/service4_images/13.jpg",
      "service_04/service4_images/14.jpg",
      "service_04/service4_images/15.jpg",
      "service_04/service4_images/16.jpg",
      "service_04/service4_images/17.jpg",
      "service_04/service4_images/18.jpg",
      "service_04/service4_images/19.jpg",
      "service_04/service4_images/20.jpg",
      "service_04/service4_images/21.jpg",
      "service_04/service4_images/22.jpg",
      "service_04/service4_images/23.jpg",
      "service_04/service4_images/24.jpg",
      "service_04/service4_images/25.jpg",
      "service_04/service4_images/26.jpg",
      "service_04/service4_images/27.jpg",
      "service_04/service4_images/28.jpg",
      "service_04/service4_images/29.jpg",
      "service_04/service4_images/30.jpg",
      "service_04/service4_images/31.jpg",
      "service_04/service4_images/32.jpg",
      "service_04/service4_images/33.jpg",
      "service_04/service4_images/34.jpg",
      "service_04/service4_images/35.jpg",
      "service_04/service4_images/36.jpg",
      "service_04/service4_images/37.jpg",
      "service_04/service4_images/38.jpg",
      "service_04/service4_images/39.jpg",
      "service_04/service4_images/40.jpg",
      "service_04/service4_images/41.jpg",
      "service_04/service4_images/42.jpg",
      "service_04/service4_images/43.jpg",
      "service_04/service4_images/44.jpg",
      "service_04/service4_images/45.jpg",
      "service_04/service4_images/46.jpg",
      "service_04/service4_images/47.jpg",
      "service_04/service4_images/48.jpg",
      "service_04/service4_images/49.jpg",
      "service_04/service4_images/50.jpg",
      "service_04/service4_images/51.jpg",
      "service_04/service4_images/52.jpg",
      "service_04/service4_images/53.jpg",
      "service_04/service4_images/54.jpg",
      "service_04/service4_images/55.jpg",
      "service_04/service4_images/56.jpg",
      "service_04/service4_images/57.jpg",
      "service_04/service4_images/58.jpg",
      "service_04/service4_images/59.jpg",
      "service_04/service4_images/60.jpg",
      "service_04/service4_images/61.jpg",
      "service_04/service4_images/62.jpg",
      "service_04/service4_images/63.jpg",
      "service_04/service4_images/64.jpg",
      "service_04/service4_images/65.jpg",
      "service_04/service4_images/66.jpg",
      "service_04/service4_images/67.jpg",
      "service_04/service4_images/68.jpg",
      "service_04/service4_images/69.jpg",
      "service_04/service4_images/70.jpg",
      "service_04/service4_images/71.jpg",
      "service_04/service4_images/72.jpg",
      "service_04/service4_images/73.jpg",
      "service_04/service4_images/74.jpg",
      "service_04/service4_images/75.jpg",
      "service_04/service4_images/76.jpg",
      "service_04/service4_images/77.jpg",
      "service_04/service4_images/78.jpg",
      "service_04/service4_images/79.jpg",
      "service_04/service4_images/80.jpg",
      "service_04/service4_images/81.jpg",
      "service_04/service4_images/82.jpg",
      "service_04/service4_images/83.jpg",
      "service_04/service4_images/84.jpg",
      "service_04/service4_images/85.jpg",
      "service_04/service4_images/86.jpg",
      "service_04/service4_images/87.jpg",
      "service_04/service4_images/88.jpg",
      "service_04/service4_images/89.jpg",
      "service_04/service4_images/90.jpg",
      "service_04/service4_images/91.jpg",
      "service_04/service4_images/92.jpg",
      "service_04/service4_images/93.jpg",
      "service_04/service4_images/94.jpg",
      "service_04/service4_images/95.jpg",
      "service_04/service4_images/96.jpg",
      "service_04/service4_images/97.jpg",
      "service_04/service4_images/98.jpg",
      "service_04/service4_images/99.jpg",
      "service_04/service4_images/100.jpg",
      "service_04/service4_images/101.jpg",
      "service_04/service4_images/102.jpg",
      "service_04/service4_images/103.jpg",
      "service_04/service4_images/104.jpg",
      "service_04/service4_images/105.jpg",
      "service_04/service4_images/106.jpg",
      "service_04/service4_images/107.jpg",
      "service_04/service4_images/108.jpg",
      "service_04/service4_images/109.jpg",
      "service_04/service4_images/110.jpg",
      "service_04/service4_images/111.jpg",
      "service_04/service4_images/112.jpg",
      "service_04/service4_images/113.jpg",
      "service_04/service4_images/114.jpg",
      "service_04/service4_images/115.jpg",
      "service_04/service4_images/116.jpg",
      "service_04/service4_images/117.jpg",
      "service_04/service4_images/118.jpg",
      "service_04/service4_images/119.jpg",
      "service_04/service4_images/120.jpg",
      "service_04/service4_images/121.jpg",
      "service_04/service4_images/122.jpg",
      "service_04/service4_images/123.jpg",
      "service_04/service4_images/124.jpg",
      "service_04/service4_images/125.jpg"
    ]
  },
  5: {
    id: 5,
    title: "Bubble Show Performer",
    description: "Are you looking for unique and memorable entertainment for your event in Dubai & UAE, Consider bubble shows Performer? Contact Now!",
    images: [
      "service_05/service5_images/1.JPG",
      "service_05/service5_images/2.JPG",
      "service_05/service5_images/3.jpg",
      "service_05/service5_images/4.jpg",
      "service_05/service5_images/5.jpg"
    ]
  },
  6: {
    id: 6,
    title: "Cartoon Mascots",
    description: "Don't miss out on this opportunity to add a unique touch to your event. Contact us today to reserve your Cartoon Mascots and give your guests a fun and memorable experience they won't forget!",
    images: [
      "service_06/service6_images/1.jpg",
      "service_06/service6_images/2.jpg",
      "service_06/service6_images/3.jpg",
      "service_06/service6_images/4.jpg",
      "service_06/service6_images/5.jpg",
      "service_06/service6_images/6.jpg",
      "service_06/service6_images/7.jpg",
      "service_06/service6_images/8.jpg",
      "service_06/service6_images/9.jpg",
      "service_06/service6_images/10.jpg",
      "service_06/service6_images/11.jpg",
      "service_06/service6_images/12.jpg",
      "service_06/service6_images/13.jpg",
      "service_06/service6_images/14.jpg",
      "service_06/service6_images/15.jpg",
      "service_06/service6_images/16.jpg",
      "service_06/service6_images/17.jpg",
      "service_06/service6_images/18.jpg",
      "service_06/service6_images/19.jpg",
      "service_06/service6_images/20.jpg",
      "service_06/service6_images/21.jpg",
      "service_06/service6_images/22.jpg",
      "service_06/service6_images/23.jpg",
      "service_06/service6_images/24.jpg",
      "service_06/service6_images/25.jpg",
      "service_06/service6_images/26.jpg",
      "service_06/service6_images/27.jpg",
      "service_06/service6_images/28.jpg"
    ]
  },
  7: {
    id: 7,
    title: "Balloon Decoration",
    description: "Professional balloon decorations to transform your event space into a magical wonderland",
    images: [
      "service_07/service7_images/1.jpg",
      "service_07/service7_images/2.jpg",
      "service_07/service7_images/3.jpg",
      "service_07/service7_images/4.jpg",
      "service_07/service7_images/5.jpg",
      "service_07/service7_images/6.jpg",
      "service_07/service7_images/7.jpg",
      "service_07/service7_images/8.jpg",
      "service_07/service7_images/9.jpg",
      "service_07/service7_images/10.jpg",
      "service_07/service7_images/11.jpg",
      "service_07/service7_images/12.jpg",
      "service_07/service7_images/13.jpg",
      "service_07/service7_images/14.jpg",
      "service_07/service7_images/15.jpg",
      "service_07/service7_images/16.jpg",
      "service_07/service7_images/17.jpg",
      "service_07/service7_images/18.jpg",
      "service_07/service7_images/19.jpg",
      "service_07/service7_images/20.jpg",
      "service_07/service7_images/21.jpg",
      "service_07/service7_images/22.jpg",
      "service_07/service7_images/23.jpg",
      "service_07/service7_images/24.jpg",
      "service_07/service7_images/25.jpg",
      "service_07/service7_images/26.jpg",
      "service_07/service7_images/27.jpg",
      "service_07/service7_images/28.jpg",
      "service_07/service7_images/29.jpg",
      "service_07/service7_images/30.jpg",
      "service_07/service7_images/31.jpg"
    ]
  },
  8: {
    id: 8,
    title: "Games for Kids",
    description: "Fun and engaging games to keep children entertained throughout your event",
    images: [
      "service_08/service8_images/1.jpg",
      "service_08/service8_images/2.jpg",
      "service_08/service8_images/3.jpg",
      "service_08/service8_images/4.jpg",
      "service_08/service8_images/5.jpg",
      "service_08/service8_images/6.jpg",
      "service_08/service8_images/7.jpg",
      "service_08/service8_images/8.jpg"
    ]
  },
  9: {
    id: 9,
    title: "Book Magician for Birthday Party",
    description: "Professional magicians to create wonder and amazement at your event",
    images: [
      "service_09/service9_images/1.jpg",
      "service_09/service9_images/2.jpg",
      "service_09/service9_images/3.jpg",
      "service_09/service9_images/4.jpg",
      "service_09/service9_images/5.jpg",
      "service_09/service9_images/6.jpg"
    ]
  },
  10: {
    id: 10,
    title: "Pony Ride, Camel Ride, and Falcon Experience",
    description: "Unique animal experiences including pony rides, camel rides, and falcon shows for memorable events",
    images: [
      "service_10/service10_images/1.jpg",
      "service_10/service10_images/2.jpg",
      "service_10/service10_images/3.jpg",
      "service_10/service10_images/4.jpg",
      "service_10/service10_images/5.jpg",
      "service_10/service10_images/6.jpg",
      "service_10/service10_images/7.jpg",
      "service_10/service10_images/8.jpg",
      "service_10/service10_images/9.jpg"
    ]
  },
  12: {
    id: 12,
    title: "Fire Performer in Dubai",
    description: "Spectacular fire performances to add excitement and thrill to your event",
    images: [
      "service_12/service12_images/1.jpg",
      "service_12/service12_images/2.jpg",
      "service_12/service12_images/3.jpg",
      "service_12/service12_images/4.jpg",
      "service_12/service12_images/5.jpg",
      "service_12/service12_images/6.jpg",
      "service_12/service12_images/7.jpg",
      "service_12/service12_images/8.jpg",
      "service_12/service12_images/9.jpg",
      "service_12/service12_images/10.jpg",
      "service_12/service12_images/11.jpg",
      "service_12/service12_images/12.jpg",
      "service_12/service12_images/13.jpg",
      "service_12/service12_images/14.jpg"
    ]
  },
  13: {
    id: 13,
    title: "Art Crafts For Kids Party",
    description: "An art and craft organizer can provide you with a variety of craft ideas that range from simple to intricate, ensuring fun for all ages. They can also assist with the setup, materials, and instructions needed to make your party a creative success.",
    images: [
      "service_13/service13_images/1.jpg",
      "service_13/service13_images/2.jpg",
      "service_13/service13_images/3.jpg",
      "service_13/service13_images/4.jpg",
      "service_13/service13_images/5.jpg",
      "service_13/service13_images/6.jpg",
      "service_13/service13_images/7.jpg",
      "service_13/service13_images/8.jpg",
      "service_13/service13_images/9.jpg",
      "service_13/service13_images/10.jpg"
    ]
  },
  14: {
    id: 14,
    title: "Water Slides & Combos",
    description: "Whether it's a birthday party, corporate event, wedding, or festival, our water slides and combos are guaranteed to bring excitement and joy to your celebration.",
    images: [
      "service_14/service14_images/1.jpg",
      "service_14/service14_images/2.jpg",
      "service_14/service14_images/3.jpg",
      "service_14/service14_images/4.jpg",
      "service_14/service14_images/5.jpg",
      "service_14/service14_images/6.jpg",
      "service_14/service14_images/7.jpg",
      "service_14/service14_images/8.jpg",
      "service_14/service14_images/9.jpg",
      "service_14/service14_images/10.jpg",
      "service_14/service14_images/11.jpg",
      "service_14/service14_images/12.jpg",
      "service_14/service14_images/13.jpg",
      "service_14/service14_images/14.jpg",
      "service_14/service14_images/15.jpg",
      "service_14/service14_images/16.jpg",
      "service_14/service14_images/17.jpg",
      "service_14/service14_images/18.jpg",
      "service_14/service14_images/19.jpg",
      "service_14/service14_images/20.jpg",
      "service_14/service14_images/21.jpg",
      "service_14/service14_images/22.jpg",
      "service_14/service14_images/23.jpg",
      "service_14/service14_images/24.jpg",
      "service_14/service14_images/25.jpg",
      "service_14/service14_images/26.jpg",
      "service_14/service14_images/27.jpg",
      "service_14/service14_images/28.jpg",
      "service_14/service14_images/29.jpg",
      "service_14/service14_images/30.jpg",
      "service_14/service14_images/31.jpg",
      "service_14/service14_images/32.jpg",
      "service_14/service14_images/33.jpg",
      "service_14/service14_images/34.jpg",
      "service_14/service14_images/35.jpg",
      "service_14/service14_images/36.jpg",
      "service_14/service14_images/37.jpg",
      "service_14/service14_images/38.jpg",
      "service_14/service14_images/39.jpg",
      "service_14/service14_images/40.jpg",
      "service_14/service14_images/41.jpg",
      "service_14/service14_images/42.jpg"
    ]
  },
  15: {
    id: 15,
    title: "Kids Furniture Rental",
    description: "Renting kids' furniture for birthday parties is one of the best ways to make the event comfortable and enjoyable. From colorful chairs to themed tables, our furniture adds a magical touch to your child's special day.",
    images: [
      "service_15/service15_images/1.jpg",
      "service_15/service15_images/2.jpg",
      "service_15/service15_images/3.jpg",
      "service_15/service15_images/4.jpg",
      "service_15/service15_images/5.jpg",
      "service_15/service15_images/6.jpg",
      "service_15/service15_images/7.jpg",
      "service_15/service15_images/8.jpg",
      "service_15/service15_images/9.jpg",
      "service_15/service15_images/10.jpg",
      "service_15/service15_images/11.jpg",
      "service_15/service15_images/12.jpg",
      "service_15/service15_images/13.jpg",
      "service_15/service15_images/14.jpg",
      "service_15/service15_images/15.jpg",
      "service_15/service15_images/16.jpg",
      "service_15/service15_images/17.jpg",
      "service_15/service15_images/18.jpg",
      "service_15/service15_images/19.jpg",
      "service_15/service15_images/20.jpg"
    ]
  }
};

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
  module.exports = SERVICES_DATA;
}
